quotes/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :quotes

end

quotes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

quotes/app/models/quote.rb
class Quote < ApplicationRecord
end

quotes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

quotes/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  # get the list of all the quotes
  def index
    # getting the list of quotes from db
    @quotes = Quote.all.order(content: :asc)
  end

  # create an instance of a quote to be used inside the new form
  def new
    @quote=Quote.new
  end

  def show
    @quote = Quote.find(params[:id])
  end

  # Post request to create the quote
  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      redirect_to quotes_path
    else
      render 'new'
    end
  end

private

  def quote_params
    params.require(:quote).permit(:content)
  end


end

quotes/app/helpers/application_helper.rb
module ApplicationHelper
end

quotes/app/helpers/quotes_helper.rb
module QuotesHelper
end

quotes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

quotes/app/views/quotes/_quote.html.erb
  <tr>
      <td><%= quote.content %></td>
      <td><%= link_to "Show", quote_path(quote)%></td>
      <td><%= link_to "Edit", edit_quote_path(quote) %></td>
</tr>
  

quotes/app/views/quotes/index.html.erb
<h1>My Quotes</h1>

<table border="1">
  <thead>
    <tr>
      <th>Quote</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
  
  <%# loop using the partial  %>
  <%= render @quotes %>
    
  </tbody>
</table>

<%= link_to "Add New Quote", new_quote_path %>

quotes/app/views/quotes/new.html.erb
<%= form_for @quote do |f| %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  <div>

<% end %>

quotes/app/views/quotes/show.html.erb
<h1>A quote</h1>

<p> Quote: <%= @quote.content %>